---
title: "Correlation and coherence"
author: "Leonardo Souto Ferreira"
date: today
format: html
toc: TRUE
execute:
  message: FALSE
  warning: FALSE
  echo: FALSE
  eval: FALSE
knitr:
  opts_knit:
    root.dir: "/home/leonardo/Doutorado/humidity_malaria_update/"
geometry:
  - margin=2cm
---

```{r, message = F, eval = TRUE}
library(tidyverse)
library(WaveletComp)
library(Rssa)
library(biwavelet)
library(ggtext)
library(ggpubr)

magnus_formula <- function(temp, dew) {
  RH <- 100 * exp((17.625 * dew) / (243.04 + dew)) / exp((17.625 * temp) / (243.04 + temp))
  return(RH)
}
```

# Figure 1

```{r, eval = TRUE}
df <- read_csv("data/Ahmedabad/dataset_Ahmedabad_2023.csv") |> filter(year >= 1997)
cases_df_ahmedabad <- read_csv("data/Ahmedabad/dataset_Ahmedabad_2023.csv") |>
  mutate(date = make_date(year, month, 1)) |>
  select(date, PF) |>
  mutate(city = "Ahmedabad")

cases_df_surat <- read_csv("data/Surat/dataset_Surat_2023.csv") |>
  mutate(date = make_date(year, month, 1)) |>
  select(date, PF) |>
  mutate(city = "Surat")

cases_df <- rbind(cases_df_ahmedabad, cases_df_surat)


p1 <- cases_df |> ggplot(aes(x = date, y = PF)) +
  facet_grid(city ~ .) +
  geom_line(color = "black", linewidth = .5) +
  # ggthemes::theme_few(16) +
  theme_minimal(base_size = 7, base_family = "sans") +
  theme(axis.line = element_line(color = "black")) +
  theme(legend.position = "bottom", axis.title.y = element_markdown()) +
  labs(
    x = "Time", y = "Observed *P. falciparum* cases", color = "",
    fill = ""
  ) +
  scale_x_date(date_breaks = "4 years", date_labels = "%Y") +
  theme(
    # plot.margin = margin(t = 30, r = 0, b = 8, l = 0, unit = "pt"),
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 0, "cm"), panel.grid.minor = element_blank(),
    text = element_text(family = "Helvetica")
  )


rh_ahmedabad_corr <- read_csv("data/Ahmedabad/dataset_Ahmedabad_2023.csv") |>
  dplyr::filter(month >= 8, month <= 9) |>
  group_by(year) |>
  summarize(cov = mean(hadISD)) |>
  left_join(read_csv("data/Ahmedabad/dataset_Ahmedabad_2023.csv") |>
    dplyr::filter(month >= 8, month <= 11) |>
    group_by(year) |>
    summarize(PF = sum(PF))) |>
  mutate(city = "Ahmedabad", covariate = "Relative Humidity")

temp_ahmedabad_corr <- read_csv("data/Ahmedabad/dataset_Ahmedabad_2023.csv") |>
  dplyr::filter(month >= 9, month <= 9) |>
  group_by(year) |>
  summarize(cov = mean(Max_Temp)) |>
  left_join(read_csv("data/Ahmedabad/dataset_Ahmedabad_2023.csv") |>
    dplyr::filter(month >= 8, month <= 11) |>
    group_by(year) |>
    summarize(PF = sum(PF))) |>
  mutate(city = "Ahmedabad", covariate = "Maximum Temperature")

rh_surat_corr <- read_csv("data/Surat/dataset_Surat_2023.csv") |>
  dplyr::filter(month >= 7, month <= 7) |>
  group_by(year) |>
  summarize(cov = mean(hadISD)) |>
  left_join(read_csv("data/Surat/dataset_Surat_2023.csv") |>
    dplyr::filter(month >= 8, month <= 11) |>
    group_by(year) |>
    summarize(PF = sum(PF))) |>
  mutate(city = "Surat", covariate = "Relative Humidity")

temp_surat_corr <- read_csv("data/Surat/dataset_Surat_2023.csv") |>
  dplyr::filter(month >= 5, month <= 9) |>
  group_by(year) |>
  summarize(cov = mean(Max_Temp)) |>
  left_join(read_csv("data/Surat/dataset_Surat_2023.csv") |>
    dplyr::filter(month >= 8, month <= 11) |>
    group_by(year) |>
    summarize(PF = sum(PF))) |>
  mutate(city = "Surat", covariate = "Maximum Temperature")

all_corr <- rh_ahmedabad_corr |>
  rbind(temp_ahmedabad_corr) |>
  rbind(rh_surat_corr) |>
  rbind(temp_surat_corr)

head(all_corr)

all_corr2 <- all_corr %>%
  mutate(
    period = case_when(
      city == "Surat" & year <= 2016 ~ "1997–2016",
      city == "Surat" & year <= 2018 ~ "2017–2018",
      city == "Surat" ~ "2019+",
      city == "Ahmedabad" & year <= 2011 ~ "1997–2011",
      city == "Ahmedabad" & year <= 2018 ~ "2012–2018",
      city == "Ahmedabad" ~ "2019+",
      TRUE ~ NA_character_
    ),
    period = factor(period, levels = c("1997–2011", "1997–2016", "2012–2018", "2017–2018", "2019+"))
  )


p2 <- all_corr2 %>%
  filter(year >= 1997) %>% # keep whatever window you want
  ggplot(aes(x = cov, y = PF, label = year)) +
  facet_grid(city ~ covariate, scales = "free") +
  geom_point(aes(color = period), size = 1) +
  geom_smooth(
    data = all_corr2 %>% filter(
      (city == "Ahmedabad" & year <= 2011) |
        (city == "Surat" & year <= 2016)
    ),
    method = "lm",
    color = "black", fill = "gray"
  ) +
  ggpubr::stat_cor(aes(label = after_stat(r.label)),
    color = "black", geom = "label", size = 2, data =
      all_corr2 %>%
        filter(
          (city == "Ahmedabad" & year <= 2011) |
            (city == "Surat" & year <= 2016)
        )
  ) +
  theme_minimal(base_size = 7, base_family = "sans") +
  theme(
    axis.line = element_line(color = "black"),
    legend.position = "none",
    axis.title.y = ggtext::element_markdown(),
    plot.margin = margin(0, 0, 0, 0, "cm"),
    panel.grid.minor = element_blank(),
    text = element_text(family = "Helvetica")
  ) +
  labs(
    x = "Average Covariate",
    y = "Observed *P. falciparum* cases",
    color = ""
  ) +
  scale_color_manual(
    values = c(
      "2012–2018" = "#7570b3",
      "2017–2018" = "#7570b3",
      "2019+"     = "#1b9e77",
      "1997–2011" = "black",
      "1997–2016" = "black"
    )
  )


print(p2)
# # ggarrange(p1, p2, ncol = 2, labels = c("A", "B"), font.label = list(family = "Times"))

library(sf)
library(patchwork)
library(basemaps)
library(ggspatial)

shape_file <- read_sf("../Datasets_Malaria/India_Data/States/Admin2.shp")
shape_file2 <- st_transform(shape_file, crs = st_crs(3857))
points <- tibble(label = c("Ahmedabad", "Surat"), latitude = c(23.0225, 21.1702), longitude = c(72.5714, 72.8311))

points |> st_as_sf(coords = c("longitude", "latitude"), crs = 4326) -> points2

endemic_states <- shape_file |> filter(ST_NM %in% c("Chhattisgarh", "Jharkhand", "Odisha", "Gujarat"))

df_station <- read_csv("../Datasets_Malaria/India_Data/India_station_list.csv")
points_sf <- st_as_sf(df_station, coords = c("long", "lat"), crs = st_crs(endemic_states))

endemic_stations <- st_join(points_sf, endemic_states, join = st_within) |>
  drop_na() |>
  left_join(df_station) |>
  rename(state = ST_NM) |>
  select(state, id, name, lat, long) |>
  mutate(name = stringr::str_to_title(name)) |>
  filter(!(name %in% c("Bhuj", "Rajkot", "Daltonganj"))) |>
  mutate(
    name = factor(name, levels = c("Ahmedabad", "Surat", "Balasore", "Bhubaneshwar", "Jharsuguda", "Birsa Munda", "Jamshedpur", "Jagdalpur", "Pbo Raipur", "Pendra Road", "Swami Vivekananda")),
    state = factor(state, levels = c("Gujarat", "Odisha", "Jharkhand", "Chhattisgarh"))
  )

print(endemic_stations)


map <- basemap_ggplot(shape_file2, map_service = "esri", map_type = "world_physical_map") +
  geom_sf(data = shape_file2, fill = NA, color = NA, linewidth = .4, color = "black", alpha = 0.8) + geom_sf(aes(color = state), data = endemic_stations, size = 1.5) +
  ggrepel::geom_label_repel(aes(label = name, geometry = geometry, color = state), data = endemic_stations, stat = "sf_coordinates", size = 2, force = 0.5, force_pull = 0.1, max.overlaps = Inf, min.segment.length = 0) +
  theme_minimal(base_size = 6, base_family = "sans") +
  annotation_north_arrow(location = "tr", which_north = "true", style = north_arrow_nautical, height = unit(1.3, "cm"), width = unit(1.3, "cm"), pad_x = unit(.3, "cm"), pad_y = unit(.3, "cm")) + annotation_scale(pad_x = unit(.4, "cm"), pad_y = unit(.3, "cm"), text_cex = .7) +
  theme_void(base_size = 7, base_family = "sans") +
  theme(text = element_text(family = "Helvetica")) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  theme(plot.margin = margin(0, 0, 0, 0, "cm"), legend.position = "none")

(p1 / (p2 | map)) + plot_layout(heights = c(1, 1)) + plot_annotation(tag_levels = "A")


ggsave("figure1.pdf", units = "mm", width = 180, height = 185, dpi = 1000)

# "#7570b3", "#1b9e77"
```

# Figure wavelets
```{r, eval = TRUE}
library(RColorBrewer)
source("R/plot_wavelet.R")
df_ahmedabad <- read_csv("data/Ahmedabad/dataset_Ahmedabad_2023.csv") |>
  mutate(date = make_date(year, month, 1))

df_ahmedabad <- df_ahmedabad |>
  mutate(
    `Relative Humidity` = stats::filter(hadISD, rep(1 / 12, 12)),
    `Maximum Temperature` = stats::filter(Max_Temp, rep(1 / 12, 12)),
    Cases = stats::filter(PF, rep(1 / 12, 12)),
    date = make_date(year, month, 1)
  ) |>
  select(date, `Relative Humidity`, `Maximum Temperature`, Cases) |>
  remove_missing()


df_surat <- read_csv("data/Surat/dataset_Surat_2023.csv")


df_surat <- df_surat |>
  mutate(
    `Relative Humidity` = stats::filter(hadISD, rep(1 / 12, 12)),
    Cases = stats::filter(PF, rep(1 / 12, 12)),
    `Maximum Temperature` = stats::filter(Max_Temp, rep(1 / 12, 12)),
    date = make_date(year, month, 1)
  ) |>
  select(date, `Relative Humidity`, `Maximum Temperature`, Cases) |>
  remove_missing()


invisible(capture.output(wc <- analyze.wavelet(df_ahmedabad, "Relative Humidity", dt = 1 / 12)))
invisible(capture.output(wc2 <- analyze.wavelet(df_ahmedabad, "Cases", dt = 1 / 12)))
invisible(capture.output(wc3 <- analyze.wavelet(df_ahmedabad, "Maximum Temperature", dt = 1 / 12)))

invisible(capture.output(wc4 <- analyze.wavelet(df_surat, "Relative Humidity", dt = 1 / 12)))
invisible(capture.output(wc5 <- analyze.wavelet(df_surat, "Cases", dt = 1 / 12)))
invisible(capture.output(wc6 <- analyze.wavelet(df_surat, "Maximum Temperature", dt = 1 / 12)))

p2 <- plot_wavelet(list(Ahmedabad = list(wc, wc2, wc3), Surat = list(wc4, wc5, wc6))) +
  theme_minimal(base_size = 7, base_family = "sans") +
  theme(axis.line = element_line(color = "black")) +
  # theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  theme(legend.key.width = unit(5.5, "lines")) +
  theme(
    legend.position = "bottom",
    legend.box.spacing = margin(-1, 0, 0, 0),
    text = element_text(family = "sans")
  ) +
  guides(fill = guide_colourbar(title.vjust = 1)) +
  scale_x_continuous(
    breaks = c(2000, (2000 + 2020) / 2, 2020),
    expand = c(0, 0),
    labels = ~ format(make_date(floor(.x), round(12 * (.x - floor(.x)) + 1), 1), "%Y")
  ) + labs(x = "Time")

# ggarrange(p1, p2, ncol = 1, heights = c(1, 1.5), labels = c("A", "B"))
print(p2)

ggsave("figure_wavelet.pdf", height = 120, width = 180, dpi = 600, unit = "mm")

df <- read_csv("data/Ahmedabad/dataset_Ahmedabad_interpolated.csv") |> filter(year(date) >= 1997)
cases_df <- read_csv("data/Ahmedabad/dataset_Ahmedabad_2023.csv") |>
  mutate(date = make_date(year, month, 1)) |>
  select(date, PF)

daily_df_ahmedabad <- df |>
  group_by(year = year(date), month = month(date)) |>
  summarize(
    max_temp = max(temp), min_temp = min(temp),
    temp = mean(temp), dew = mean(dew), humidity = mean(humidity)
  ) |>
  ungroup() |>
  mutate(
    humidity = stats::filter(humidity, rep(1 / 12, 12)),
    temp = stats::filter(temp, rep(1 / 12, 12)),
    max_temp = stats::filter(max_temp, rep(1 / 12, 12)),
    min_temp = stats::filter(min_temp, rep(1 / 12, 12)),
    date = make_date(year, month, 1)
  ) |>
  left_join(cases_df) |>
  remove_missing()

df <- read_csv("data/Surat/dataset_Surat_hadISD_raw.csv") |>
  filter(year(date) >= 1997) |>
  rename(humidity = RH)
cases_df <- read_csv("data/Surat/dataset_Surat_2023.csv") |>
  mutate(date = make_date(year, month, 1)) |>
  select(date, PF)

daily_df_surat <- df |>
  group_by(year = year(date), month = month(date)) |>
  summarize(
    max_temp = max(temp), min_temp = min(temp),
    temp = mean(temp), dew = mean(dew), humidity = mean(humidity)
  ) |>
  ungroup() |>
  mutate(
    humidity = stats::filter(humidity, rep(1 / 12, 12)),
    temp = stats::filter(temp, rep(1 / 12, 12)),
    max_temp = stats::filter(max_temp, rep(1 / 12, 12)),
    min_temp = stats::filter(min_temp, rep(1 / 12, 12)),
    date = make_date(year, month, 1)
  ) |>
  left_join(cases_df) |>
  remove_missing()


invisible(capture.output(wc <- analyze.coherency(daily_df_ahmedabad, my.pair = c("humidity", "PF"), dt = 1 / 12, lowerPeriod = 0.5, date.format = "%Y-%m-%d", loess.span = 0)))
invisible(capture.output(wc2 <- analyze.coherency(daily_df_ahmedabad, my.pair = c("temp", "PF"), dt = 1 / 12, lowerPeriod = 0.5, date.format = "%Y-%m-%d", loess.span = 0)))
invisible(capture.output(wc3 <- analyze.coherency(daily_df_ahmedabad, my.pair = c("max_temp", "PF"), dt = 1 / 12, lowerPeriod = 0.5, date.format = "%Y-%m-%d", loess.span = 0)))

invisible(capture.output(wc4 <- analyze.coherency(daily_df_surat, my.pair = c("humidity", "PF"), dt = 1 / 12, lowerPeriod = 0.5, date.format = "%Y-%m-%d", loess.span = 0)))
invisible(capture.output(wc5 <- analyze.coherency(daily_df_surat, my.pair = c("temp", "PF"), dt = 1 / 12, lowerPeriod = 0.5, date.format = "%Y-%m-%d", loess.span = 0)))
invisible(capture.output(wc6 <- analyze.coherency(daily_df_surat, my.pair = c("max_temp", "PF"), dt = 1 / 12, lowerPeriod = 0.5, date.format = "%Y-%m-%d", loess.span = 0)))

# wc.image(wc, "wp")
p1 <- plot_wavelet_coherence(list(Ahmedabad = list(wc, wc3), Surat = list(wc4, wc6)), "wp") +
  labs(x = "Time") + theme_minimal(base_size = 7, base_family = "sans") +
  theme(text = element_text(family = "sans"))
# p2 <- plot_wavelet_coherence(list(Ahmedabad = list(wc, wc3), Surat = list(wc4, wc6)), "wc") +
# labs(color = "Coherence", fill = "Coherence", x = "Time")
# ggarrange(p1, p2, ncol = 1, labels = c("A", "B"), font.label = list(family = "Times"))
print(p1)


ggsave("figures/figure_coherence.pdf", height = 120, width = 180, dpi = 600, unit = "mm")
```

# Figure 2 

```{r, eval = TRUE}
source("R/simulation_functions.R")
source("R/mcap.R")
# source("fitting/cleaning_profile_results.R")

all_res <- read_csv("aggregated_results/profile_Surat_Max_Temp_1997_2016_5_9.csv") |> filter(
  rho >= 0.01,
  alpha <= 1,
  bH < 0
)

all_res |> slice_max(loglik, n = 1)
k <- 1
surat_result_temp <- all_res |>
  get_top_sample(k = k) |>
  predict_model("Surat",
    n_sims = 1000,
    model = "inf_exponent", covariate = "Max_Temp",
    start_year = 1997, start_month = 1,
    end_year = 2016, end_month = 12,
    end_year_prediction = 2023, end_month_prediction = 12,
    window_start = 5, window_end = 9,
    dataset = "data/Surat/dataset_Surat_2023.csv", output_format = "data.frame",
  ) |>
  mutate(city = "Surat")

all_res <- read_csv("aggregated_results/profile_Surat_hadISD_1997_2016_7_7.csv") |>
  filter(rho >= 0.01)
all_res |> slice_max(loglik, n = 1)

k <- 1
surat_result_rh <- all_res |>
  get_top_sample(k = k) |>
  predict_model("Surat",
    n_sims = 1000,
    model = "inf_exponent", covariate = "hadISD",
    start_year = 1997, start_month = 1,
    end_year = 2016, end_month = 12,
    end_year_prediction = 2023, end_month_prediction = 12,
    window_start = 7, window_end = 7,
    dataset = "data/Surat/dataset_Surat_2023.csv", output_format = "data.frame",
  ) |>
  mutate(city = "Surat")

# all_res <- read_csv("test_2024_10_28_1/output_Surat_baseline_hadISD_1997_1_2011_12_refined_second.csv")
# k <- 1
# surat_result_baseline <- all_res |>
#   filter(loglik >= -1000, loglik <= -800, rho >= 0.01) |>
#   get_top_sample(k = k) |>
#   predict_model_parmat("Surat",
#     n_sims = 1000,
#     model = "baseline", covariate = "hadISD",
#     start_year = 1997, start_month = 1,
#     end_year = 2011, end_month = 12,
#     end_year_prediction = 2023, end_month_prediction = 12,
#     window_start = 8, window_end = 9,
#     dataset = "data/Surat/dataset_Surat_2023.csv", output_format = "data.frame"
#   ) |>
#   mutate(city = "Surat")

all_res <- read_csv("aggregated_results/profile_Ahmedabad_hadISD_1997_2011_8_9.csv") |>
  filter(mode == "refined_second", rho >= 0.01) |>
  select(-mode, -profile_var, -source_file)
all_res |> slice_max(loglik, n = 1)

k <- 1
ahmedabad_result_rh <- all_res |>
  get_top_sample(k = k) |>
  predict_model("Ahmedabad",
    n_sims = 1000,
    model = "inf_exponent", covariate = "hadISD",
    start_year = 1997, start_month = 1,
    end_year = 2011, end_month = 12,
    end_year_prediction = 2023, end_month_prediction = 12,
    window_start = 8, window_end = 9,
    dataset = "data/Ahmedabad/dataset_Ahmedabad_2023.csv", output_format = "data.frame"
  ) |>
  mutate(city = "Ahmedabad")

all_res <- read_csv("aggregated_results/profile_Ahmedabad_Max_Temp_1997_2011_9_9.csv") |> filter(rho >= 0.01)
all_res |> slice_max(loglik, n = 1)

k <- 1
ahmedabad_result_temp <- all_res |>
  get_top_sample(k = k) |>
  predict_model("Ahmedabad",
    n_sims = 1000,
    model = "inf_exponent", covariate = "Max_Temp",
    start_year = 1997, start_month = 1,
    end_year = 2011, end_month = 12,
    end_year_prediction = 2023, end_month_prediction = 12,
    window_start = 9, window_end = 9,
    dataset = "data/Ahmedabad/dataset_Ahmedabad_2023.csv", output_format = "data.frame"
  ) |>
  mutate(city = "Ahmedabad")


# all_res <- read_csv("test_2024_10_28_1/output_Ahmedabad_baseline_hadISD_1997_1_2011_12_refined_second.csv")
# k <- 2
# ahmedabad_result_baseline <- all_res |>
#   filter(loglik >= -1000, loglik <= -800, rho >= 0.01) |>
#   get_top_sample(k = k) |>
#   predict_model_parmat("Ahmedabad",
#     n_sims = 1000,
#     model = "baseline", covariate = "hadISD",
#     start_year = 1997, start_month = 1,
#     end_year = 2011, end_month = 12,
#     end_year_prediction = 2023, end_month_prediction = 12,
#     window_start = 8, window_end = 9,
#     dataset = "data/Ahmedabad/dataset_Ahmedabad_2023.csv", output_format = "data.frame"
#   ) |>
#   mutate(city = "Ahmedabad")

dataset <- rbind(
  ahmedabad_result_rh |> mutate(covariate = "Relative Humidity"),
  ahmedabad_result_temp |> mutate(covariate = "Maximum Temperature")
) |>
  rbind(
    surat_result_rh |> mutate(covariate = "Relative Humidity")
  ) |>
  rbind(surat_result_temp |> mutate(covariate = "Maximum Temperature"))

CI <- 0.95
font_size <- 18
res <- dataset |> filter(type == "data", city == "Ahmedabad")
max_res <- max(res$PF)
training <- dataset |> filter(type == "training", city == "Ahmedabad")


colors <- c("#000000", "#7570b3", "#1b9e77")
colors2 <- c("#FFFFFF", "#D5CCE6", "#8af1b9")

p1 <- dataset |>
  filter(city == "Ahmedabad") |>
  ggplot(aes(
    x = time, y = PF, fill = type, color = type
  )) +
  facet_wrap(~covariate) +
  ggdist::stat_lineribbon(.width = CI, linewidth = 0.5) +
  theme_minimal(,
    base_size = 7, base_family = "sans"
  ) +
  theme(axis.line = element_line(color = "black")) +
  geom_vline(xintercept = max(training$time), linetype = "dashed") +
  theme(legend.position = "bottom", axis.title.y = element_markdown()) +
  labs(
    x = "Time", y = "Observed *P. falciparum* cases", color = "",
    fill = ""
  ) +
  theme(legend.position = "bottom") +
  scale_color_manual(
    values = colors, , labels = c("Data", "Training", "Prediction"),
    breaks = c("data", "training", "prediction")
  ) +
  scale_fill_manual(
    values = colors2, drop = TRUE, labels = c("Data", "Training", "Prediction"),
    breaks = c("data", "training", "prediction")
  ) +
  coord_cartesian(ylim = c(0, 1600)) +
  # labs(title = "Ahmedabad") +
  theme(
    legend.position = "bottom",
    legend.box.spacing = margin(-1, 0, 0, 0),
    panel.grid.minor = element_blank()
  ) +
  labs(title = "Ahmedabad") +
  theme(
    legend.key.height = unit(10, "pt"),
    legend.key.width = unit(10, "pt"),
    plot.margin = margin(
      t = 2, r = 10, b = 2, l = 2, # pt
      unit = "pt"
    )
  )


print(p1)


# ggarrange(p1, p2, ncol = 2, labels = c("A", "B"))

ggsave("figure2.pdf", height = 70, width = 180, dpi = 1000, unit = "mm")


CI <- 0.95
font_size <- 18
res <- dataset |> filter(type == "data", city == "Surat")
max_res <- max(res$PF)
training <- dataset |> filter(type == "training", city == "Surat")


colors <- c("#000000", "#7570b3", "#1b9e77")
colors2 <- c("#FFFFFF", "#D5CCE6", "#8af1b9")

p1 <- dataset |>
  filter(city == "Surat") |>
  ggplot(aes(
    x = time, y = PF, fill = type, color = type
  )) +
  facet_wrap(~covariate) +
  ggdist::stat_lineribbon(.width = CI, linewidth = 0.5) +
  theme_minimal(,
    base_size = 7, base_family = "sans"
  ) +
  theme(axis.line = element_line(color = "black")) +
  geom_vline(xintercept = max(training$time), linetype = "dashed") +
  theme(legend.position = "bottom", axis.title.y = element_markdown()) +
  labs(
    x = "Time", y = "Observed *P. falciparum* cases", color = "",
    fill = ""
  ) +
  theme(legend.position = "bottom") +
  scale_color_manual(
    values = colors, , labels = c("Data", "Training", "Prediction"),
    breaks = c("data", "training", "prediction")
  ) +
  scale_fill_manual(
    values = colors2, drop = TRUE, labels = c("Data", "Training", "Prediction"),
    breaks = c("data", "training", "prediction")
  ) +
  coord_cartesian(ylim = c(0, 2000)) +
  # labs(title = "Ahmedabad") +
  theme(
    legend.position = "bottom",
    legend.box.spacing = margin(-1, 0, 0, 0),
    panel.grid.minor = element_blank()
  ) +
  labs(title = "Surat") +
  theme(
    legend.key.height = unit(10, "pt"),
    legend.key.width = unit(10, "pt"),
    plot.margin = margin(
      t = 2, r = 10, b = 2, l = 2, # pt
      unit = "pt"
    )
  )


print(p1)


# ggarrange(p1, p2, ncol = 2, labels = c("A", "B"))

ggsave("figure3.pdf", height = 70, width = 180, dpi = 1000, unit = "mm")
```


# Figure 3

```{r, eval = FALSE}
df <- read_csv("prediction_files/parameters_yearly_prediction Ahmedabad hadISD 13.csv")
city <- "Ahmedabad"
covariate <- "hadISD"
prediction_window <- 13
window_start <- 8
window_end <- 9
dat_df <- str_glue("data/{city}/dataset_{city}_2023.csv")
result <- df |>
  dplyr::filter(sample == 83) |>
  dplyr::select(-sample) |>
  simulate_yearly_prediction(
    city = city,
    n_sims = 1000,
    model = "inf_exponent", covariate = covariate,
    start_year = 1997, start_month = 1,
    end_year = 2011, end_month = 12,
    end_year_prediction = 2023, end_month_prediction = 12,
    prediction_window = prediction_window,
    window_start = window_start, window_end = window_end,
    dataset = dat_df, output_format = c("data.frame", "pomps"), ignore_covid = TRUE,
    actual_end_year = 2011, actual_end_month = 12
  )

ignore_covid <- result$ignore_covid
training <- result$training$training |>
  mutate(type = if_else(.id == "data", "data", "training"))

prediction <- result$prediction |>
  bind_rows() |>
  mutate(type = if_else(.id == "data", "data", "prediction"))

# print(prediction, n = 1000)

dataset <- rbind(training, prediction)
res <- dataset |> filter(type == "data")
max_res <- max(res$PF)
training <- dataset |> filter(type == "training")

# print(result$complete_data)
complete_data <- result$complete_data |>
  dplyr::select(time, PF) |>
  mutate(type = "data")
# if (ignore_covid) {
dataset_ahmedabad_hadisd <- dataset |>
  dplyr::select(time, PF, type) |>
  dplyr::filter(type != "data") |>
  rbind(complete_data) |>
  arrange(time, type) |>
  mutate(covid = if_else(floor(time) == 2020 & type == "data", "sim", "nao")) |>
  mutate(city = "Ahmedabad", covariate = "Relative Humidity")

###########
df <- read_csv("prediction_files/parameters_yearly_prediction Ahmedabad Max_Temp 14.csv")
city <- "Ahmedabad"
covariate <- "Max_Temp"
prediction_window <- 14
window_start <- 9
window_end <- 9
dat_df <- str_glue("data/{city}/dataset_{city}_2023.csv")
result <- df |>
  dplyr::filter(sample == 83) |>
  dplyr::select(-sample) |>
  simulate_yearly_prediction(
    city = city,
    n_sims = 1000,
    model = "inf_exponent", covariate = covariate,
    start_year = 1997, start_month = 1,
    end_year = 2011, end_month = 12,
    end_year_prediction = 2023, end_month_prediction = 12,
    prediction_window = prediction_window,
    window_start = window_start, window_end = window_end,
    dataset = dat_df, output_format = c("data.frame", "pomps"), ignore_covid = TRUE,
    actual_end_year = 2011, actual_end_month = 12
  )

ignore_covid <- result$ignore_covid
training <- result$training$training |>
  mutate(type = if_else(.id == "data", "data", "training"))

prediction <- result$prediction |>
  bind_rows() |>
  mutate(type = if_else(.id == "data", "data", "prediction"))

# print(prediction, n = 1000)

dataset <- rbind(training, prediction)
res <- dataset |> filter(type == "data")
max_res <- max(res$PF)
training <- dataset |> filter(type == "training")

# print(result$complete_data)
complete_data <- result$complete_data |>
  dplyr::select(time, PF) |>
  mutate(type = "data")
# if (ignore_covid) {
dataset_ahmedabad_temp <- dataset |>
  dplyr::select(time, PF, type) |>
  dplyr::filter(type != "data") |>
  rbind(complete_data) |>
  arrange(time, type) |>
  mutate(covid = if_else(floor(time) == 2020 & type == "data", "sim", "nao")) |>
  mutate(city = "Ahmedabad", covariate = "Maximum Temperature")

##############
df <- read_csv("prediction_files/parameters_yearly_prediction Surat hadISD 7.csv")
city <- "Surat"
covariate <- "hadISD"
prediction_window <- 7
window_start <- 5
window_end <- 7
dat_df <- str_glue("data/{city}/dataset_{city}_2023.csv")
result <- df |>
  dplyr::filter(sample == 2) |>
  dplyr::select(-sample) |>
  simulate_yearly_prediction(
    city = city,
    n_sims = 1000,
    model = "inf_exponent", covariate = covariate,
    start_year = 1997, start_month = 1,
    end_year = 2011, end_month = 12,
    end_year_prediction = 2023, end_month_prediction = 12,
    prediction_window = prediction_window,
    window_start = window_start, window_end = window_end,
    dataset = dat_df, output_format = c("data.frame", "pomps"), ignore_covid = TRUE,
    actual_end_year = 2011, actual_end_month = 12
  )

ignore_covid <- result$ignore_covid
training <- result$training$training |>
  mutate(type = if_else(.id == "data", "data", "training"))

prediction <- result$prediction |>
  bind_rows() |>
  mutate(type = if_else(.id == "data", "data", "prediction"))

# print(prediction, n = 1000)

dataset <- rbind(training, prediction)
res <- dataset |> filter(type == "data")
max_res <- max(res$PF)
training <- dataset |> filter(type == "training")

# print(result$complete_data)
complete_data <- result$complete_data |>
  dplyr::select(time, PF) |>
  mutate(type = "data")
# if (ignore_covid) {
dataset_surat_hadisd <- dataset |>
  dplyr::select(time, PF, type) |>
  dplyr::filter(type != "data") |>
  rbind(complete_data) |>
  arrange(time, type) |>
  mutate(covid = if_else(floor(time) == 2020 & type == "data", "sim", "nao")) |>
  mutate(city = "Surat", covariate = "Relative Humidity")

##########
df <- read_csv("prediction_files/parameters_yearly_prediction Surat Max_Temp 8.csv")
city <- "Surat"
covariate <- "Max_Temp"
prediction_window <- 8
window_start <- 5
window_end <- 7
dat_df <- str_glue("data/{city}/dataset_{city}_2023.csv")
result <- df |>
  dplyr::filter(sample == 92) |>
  dplyr::select(-sample) |>
  simulate_yearly_prediction(
    city = city,
    n_sims = 1000,
    model = "inf_exponent", covariate = covariate,
    start_year = 1997, start_month = 1,
    end_year = 2011, end_month = 12,
    end_year_prediction = 2023, end_month_prediction = 12,
    prediction_window = prediction_window,
    window_start = window_start, window_end = window_end,
    dataset = dat_df, output_format = c("data.frame", "pomps"), ignore_covid = TRUE,
    actual_end_year = 2011, actual_end_month = 12
  )

ignore_covid <- result$ignore_covid
training <- result$training$training |>
  mutate(type = if_else(.id == "data", "data", "training"))

prediction <- result$prediction |>
  bind_rows() |>
  mutate(type = if_else(.id == "data", "data", "prediction"))

# print(prediction, n = 1000)

dataset <- rbind(training, prediction)
res <- dataset |> filter(type == "data")
max_res <- max(res$PF)
training <- dataset |> filter(type == "training")

# print(result$complete_data)
complete_data <- result$complete_data |>
  dplyr::select(time, PF) |>
  mutate(type = "data")
# if (ignore_covid) {
dataset_surat_temp <- dataset |>
  dplyr::select(time, PF, type) |>
  dplyr::filter(type != "data") |>
  rbind(complete_data) |>
  arrange(time, type) |>
  mutate(covid = if_else(floor(time) == 2020 & type == "data", "sim", "nao")) |>
  mutate(city = "Surat", covariate = "Maximum Temperature")

########

dataset_all <- rbind(dataset_ahmedabad_hadisd, dataset_ahmedabad_temp) |>
  rbind(dataset_surat_hadisd) |>
  rbind(dataset_surat_temp)

head(dataset_all)


colors <- c("#000000", "#7570b3", "#1b9e77")
colors2 <- c("#FFFFFF", "#D5CCE6", "#8af1b9")

p1 <- dataset_all |>
  ggplot(aes(
    x = time, y = PF, fill = type, color = type
  )) +
  facet_grid(covariate ~ city) +
  ggdist::stat_lineribbon(
    .width = CI, linewidth = 0.8, na.rm = TRUE,
  ) +
  theme_minimal(22) +
  theme(axis.line = element_line(color = "black")) +
  geom_vline(xintercept = max(training$time), linetype = "dashed") +
  theme(legend.position = "bottom", axis.title.y = element_markdown()) +
  labs(
    x = "Time", y = "Observed *P. falciparum* cases", color = "",
    fill = ""
  ) +
  theme(legend.position = "bottom") +
  scale_color_manual(
    values = colors, labels = c("Data", "Training", "Prediction"),
    breaks = c("data", "training", "prediction")
  ) +
  scale_fill_manual(
    values = colors2, drop = TRUE, labels = c("Data", "Training", "Prediction"),
    breaks = c("data", "training", "prediction")
  ) +
  coord_cartesian(ylim = c(0, 2000)) +
  # labs(title = "Ahmedabad") +
  theme(
    legend.position = "bottom",
    legend.box.spacing = margin(-1, 0, 0, 0),
    panel.grid.minor = element_blank(),
    text = element_text(family = "Times")
  )

print(p1)

ggsave("figure3_science.pdf", height = 7, width = 14, dpi = 1000)


```

## Figure covariates
```{r, eval = TRUE}
city <- "Ahmedabad"
covariate <- "hadISD"
prediction_window <- 13
window_start <- 8
window_end <- 9
dat_df <- str_glue("data/{city}/dataset_{city}_2023.csv")


rh_ahm <- read_csv(dat_df) |>
  filter(month >= window_start, month <= window_end) |>
  group_by(year) |>
  summarize(mean_covariate = mean(!!sym(covariate))) |>
  mutate(city = city, covariate = if_else(covariate == "hadISD", "Relative Humidity", "Maximum Temperature"))

city <- "Ahmedabad"
covariate <- "Max_Temp"
prediction_window <- 13
window_start <- 9
window_end <- 9
dat_df <- str_glue("data/{city}/dataset_{city}_2023.csv")

temp_ahm <- read_csv(dat_df) |>
  filter(month >= window_start, month <= window_end) |>
  group_by(year) |>
  summarize(mean_covariate = mean(!!sym(covariate))) |>
  mutate(city = city, covariate = if_else(covariate == "hadISD", "Relative Humidity", "Maximum Temperature"))


city <- "Surat"
covariate <- "hadISD"
prediction_window <- 17
window_start <- 7
window_end <- 7
dat_df <- str_glue("data/{city}/dataset_{city}_2023.csv")


rh_surat <- read_csv(dat_df) |>
  filter(month >= window_start, month <= window_end) |>
  group_by(year) |>
  summarize(mean_covariate = mean(!!sym(covariate))) |>
  mutate(city = city, covariate = if_else(covariate == "hadISD", "Relative Humidity", "Maximum Temperature"))

city <- "Surat"
covariate <- "Max_Temp"
prediction_window <- 17
window_start <- 5
window_end <- 9
dat_df <- str_glue("data/{city}/dataset_{city}_2023.csv")

temp_surat <- read_csv(dat_df) |>
  filter(month >= window_start, month <= window_end) |>
  group_by(year) |>
  summarize(mean_covariate = mean(!!sym(covariate))) |>
  mutate(city = city, covariate = if_else(covariate == "hadISD", "Relative Humidity", "Maximum Temperature"))

all_df <- rbind(rh_ahm, temp_ahm) |>
  rbind(rh_surat) |>
  rbind(temp_surat) |>
  group_by(city, covariate) |>
  mutate(mean_covariate = (mean_covariate - min(mean_covariate)) / (max(mean_covariate) - min(mean_covariate))) |>
  ungroup() |>
  mutate(
    type = case_when(
      city == "Surat" & year <= 2015 ~ "a",
      city == "Surat" & year <= 2018 ~ "b",
      city == "Surat" ~ "c",
      city == "Ahmedabad" & year <= 2011 ~ "a",
      city == "Ahmedabad" & year <= 2018 ~ "b",
      city == "Ahmedabad" ~ "c",
      TRUE ~ NA_character_
    )
  )

print(all_df)

colors <- c("#000000", "#7570b3", "#1b9e77")


all_df |> ggplot(aes(x = year, y = mean_covariate, color = type, group = 1)) +
  facet_grid(cols = vars(covariate), rows = vars(city), scales = "free_y") +
  geom_step(direction = "mid") +
  scale_color_manual(
    values = colors,
    breaks = c("a", "b", "c")
  ) +
  theme_bw(16) +
  theme(legend.position = "none") +
  labs(x = "Year", y = "Scaled covariate")

ggsave("figure_covariates.pdf", dpi = 600, width = 10, height = 7)

```